// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/winch/winch.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class WinchImpl;

/**
 * @brief Enable simple Winch actions.
 */
class Winch : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto winch = Winch(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Winch(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto winch = Winch(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Winch(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~Winch() override;


    /**
     * @brief 
     */
    enum class WinchAction {
        Relaxed, /**< @brief. */
        RelativeLengthControl, /**< @brief. */
        RateControl, /**< @brief. */
        Lock, /**< @brief. */
        Deliver, /**< @brief. */
        Hold, /**< @brief. */
        Retract, /**< @brief. */
        LoadLine, /**< @brief. */
        AbandonLine, /**< @brief. */
        LoadPayload, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `Winch::WinchAction`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Winch::WinchAction const& winch_action);





    /**
     * @brief Possible results returned for action requests.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Request was successful. */
        NoSystem, /**< @brief No system is connected. */
        ConnectionError, /**< @brief Connection error. */
        Busy, /**< @brief Vehicle is busy. */
        CommandDenied, /**< @brief Command refused by vehicle. */
        CommandDeniedLandedStateUnknown, /**< @brief Command refused because landed state is unknown. */
        CommandDeniedNotLanded, /**< @brief Command refused because vehicle not landed. */
        Timeout, /**< @brief Request timed out. */
        VtolTransitionSupportUnknown, /**< @brief Hybrid/VTOL transition support is unknown. */
        NoVtolTransitionSupport, /**< @brief Vehicle does not support hybrid/VTOL transitions. */
        ParameterError, /**< @brief Error getting or setting parameter. */
        Unsupported, /**< @brief Action not supported. */
        Failed, /**< @brief Action failed. */
    };

    /**
     * @brief Stream operator to print information about a `Winch::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Winch::Result const& result);



    /**
     * @brief Callback type for asynchronous Winch calls.
     */
    using ResultCallback = std::function<void(Result)>;




    /**
     * @brief Allow motor to freewheel.
     *
     * This function is non-blocking. See 'winch_relax' for the blocking counterpart.
     */
    void winch_relax_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Allow motor to freewheel.
     *
     * This function is blocking. See 'winch_relax_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_relax(uint32_t instance) const;




    /**
     * @brief Wind or unwind specified length of line, optionally using specified rate.
     *
     * This function is non-blocking. See 'winch_relative_length_control' for the blocking counterpart.
     */
    void winch_relative_length_control_async(uint32_t instance, float length, float rate, const ResultCallback callback);



    /**
     * @brief Wind or unwind specified length of line, optionally using specified rate.
     *
     * This function is blocking. See 'winch_relative_length_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_relative_length_control(uint32_t instance, float length, float rate) const;




    /**
     * @brief Wind or unwind line at specified rate.
     *
     * This function is non-blocking. See 'winch_rate_control' for the blocking counterpart.
     */
    void winch_rate_control_async(uint32_t instance, float rate, const ResultCallback callback);



    /**
     * @brief Wind or unwind line at specified rate.
     *
     * This function is blocking. See 'winch_rate_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_rate_control(uint32_t instance, float rate) const;




    /**
     * @brief Perform the locking sequence to relieve motor while in the fully retracted position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_lock' for the blocking counterpart.
     */
    void winch_lock_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Perform the locking sequence to relieve motor while in the fully retracted position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_lock_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_lock(uint32_t instance) const;




    /**
     * @brief Sequence of drop, slow down, touch down, reel up, lock. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_deliver' for the blocking counterpart.
     */
    void winch_deliver_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Sequence of drop, slow down, touch down, reel up, lock. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_deliver_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_deliver(uint32_t instance) const;




    /**
     * @brief Engage motor and hold current position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_hold' for the blocking counterpart.
     */
    void winch_hold_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Engage motor and hold current position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_hold_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_hold(uint32_t instance) const;




    /**
     * @brief Return the reel to the fully retracted position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_retract' for the blocking counterpart.
     */
    void winch_retract_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Return the reel to the fully retracted position. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_retract_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_retract(uint32_t instance) const;




    /**
     * @brief Load the reel with line. The winch will calculate the total loaded length and stop when the tension exceeds a threshold. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_load_line' for the blocking counterpart.
     */
    void winch_load_line_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Load the reel with line. The winch will calculate the total loaded length and stop when the tension exceeds a threshold. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_load_line_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_load_line(uint32_t instance) const;




    /**
     * @brief Spool out the entire length of the line. Only action and instance command parameters are used, others are ignored.
     *
     * This function is non-blocking. See 'winch_abandon_line' for the blocking counterpart.
     */
    void winch_abandon_line_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Spool out the entire length of the line. Only action and instance command parameters are used, others are ignored.
     *
     * This function is blocking. See 'winch_abandon_line_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_abandon_line(uint32_t instance) const;




    /**
     * @brief Spools out just enough to present the hook to the user to load the payload. Only action and instance command parameters are used, others are ignored
     *
     * This function is non-blocking. See 'winch_load_payload' for the blocking counterpart.
     */
    void winch_load_payload_async(uint32_t instance, const ResultCallback callback);



    /**
     * @brief Spools out just enough to present the hook to the user to load the payload. Only action and instance command parameters are used, others are ignored
     *
     * This function is blocking. See 'winch_load_payload_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result winch_load_payload(uint32_t instance) const;




    /**
     * @brief Copy constructor.
     */
    Winch(const Winch& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const Winch& operator=(const Winch&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<WinchImpl> _impl;
};

} // namespace mavsdk